# Generated by Django 2.1.5 on 2020-11-28 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 5, 45, 265582), verbose_name='date published'),
        ),
    ]
