# Generated by Django 2.1.5 on 2020-11-28 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201128_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 15, 30, 21, 534242), verbose_name='date published'),
        ),
    ]
