# Generated by Django 2.1.5 on 2020-11-29 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201128_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 14, 40, 4, 368113), verbose_name='date published'),
        ),
    ]
